name: Packer

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1


    - name: Install Packer
      run: |
        wget https://releases.hashicorp.com/packer/1.8.5/packer_1.8.5_linux_amd64.zip
        unzip -o packer_1.8.5_linux_amd64.zip -d packer_temp
        sudo mv packer_temp/packer /usr/local/bin/

        
    - name: Packer Validate
      run: packer validate ./packer.json

    - name: Packer Build
      run: packer build -debug ./packer.json